"use client";

import type { Settings } from "@/components/Providers";
import { dateLabel } from "@/lib/utils";

export type PdfTable = {
  title?: string;
  note?: string;
  head: string[];
  body: (string | number)[][];
  align?: ("left" | "right" | "center")[];
};

export type PdfOptions = {
  settings: Settings | null;
  title: string;
  subtitle?: string;
  period?: string;
  meta?: { label: string; value: string }[];
  tables: PdfTable[];
  filename: string;
  landscape?: boolean;
};

/** Builds a print-ready PDF with the school letterhead on every page. */
export async function buildPdf(opts: PdfOptions) {
  const { default: JsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const school = opts.settings?.school;
  const pdf = opts.settings?.pdf;
  const createdBy = school?.createdBy ?? "Created by Mr. AbdulWahid";
  const doc = new JsPDF({
    unit: "pt",
    format: pdf?.pageSize === "LETTER" ? "letter" : "a4",
    orientation: opts.landscape || pdf?.orientation === "landscape" ? "landscape" : "portrait",
  });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const marginX = 34;

  const header = () => {
    let y = 46;
    doc.setFillColor(16, 177, 136);
    doc.rect(0, 0, pageW, 6, "F");
    doc.setTextColor(6, 78, 66);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.text(school?.name || "Iqra Islamic Education School", pageW / 2, y, { align: "center" });
    y += 14;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(80, 90, 100);
    doc.text(school?.tagline || "School Student & Teacher Recorder", pageW / 2, y, { align: "center" });
    y += 12;
    doc.setFontSize(8);
    doc.text(
      [school?.address, school?.phone ? `Phone: ${school.phone}` : "", school?.email].filter(Boolean).join("  ·  "),
      pageW / 2,
      y,
      { align: "center" },
    );
    y += 20;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(20, 30, 40);
    doc.text(opts.title, pageW / 2, y, { align: "center" });
    y += 13;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(90, 100, 110);
    const sub = [opts.subtitle, opts.period].filter(Boolean).join("  ·  ");
    if (sub) {
      doc.text(sub, pageW / 2, y, { align: "center" });
      y += 12;
    }
    doc.setDrawColor(210, 220, 228);
    doc.line(marginX, y, pageW - marginX, y);
    return y + 12;
  };

  let start = header();

  if (opts.meta?.length) {
    doc.setFontSize(8.5);
    doc.setTextColor(60, 70, 80);
    const cols = 3;
    opts.meta.forEach((m, i) => {
      const col = i % cols;
      const row = Math.floor(i / cols);
      const x = marginX + col * ((pageW - marginX * 2) / cols);
      const yy = start + row * 12;
      doc.text(`${m.label}: `, x, yy);
      doc.setFont("helvetica", "bold");
      doc.text(String(m.value), x + doc.getTextWidth(`${m.label}: `), yy);
      doc.setFont("helvetica", "normal");
    });
    start += Math.ceil(opts.meta.length / cols) * 12 + 8;
  }

  opts.tables.forEach((t, index) => {
    if (t.title) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10.5);
      doc.setTextColor(10, 110, 90);
      doc.text(t.title, marginX, start + 4);
      start += 10;
    }
    autoTable(doc, {
      startY: start,
      head: [t.head],
      body: t.body.length ? t.body : [["No records for this filter"]],
      theme: "grid",
      styles: { fontSize: 8, cellPadding: 3.5, lineColor: [224, 231, 238], textColor: [35, 44, 58] },
      headStyles: { fillColor: [7, 114, 92], textColor: 255, fontStyle: "bold", fontSize: 8 },
      alternateRowStyles: { fillColor: [246, 250, 252] },
      columnStyles: Object.fromEntries(
        (t.align ?? []).map((a, i) => [i, { halign: a }]),
      ) as never,
      margin: { left: marginX, right: marginX },
      didDrawPage: () => {
        footer();
      },
    });
    if (t.note) {
      const after = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable;
      start = after.finalY + 12;
      doc.setFontSize(8);
      doc.setTextColor(90, 100, 110);
      doc.text(t.note, marginX, start);
      start += 14;
    } else {
      const after = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable;
      start = after.finalY + (index === opts.tables.length - 1 ? 0 : 16);
    }
  });

  function footer() {
    const pages = doc.getNumberOfPages();
    const current = doc.getCurrentPageInfo().pageNumber;
    doc.setDrawColor(210, 220, 228);
    doc.line(marginX, pageH - 34, pageW - marginX, pageH - 34);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.6);
    doc.setTextColor(110, 120, 130);
    doc.text(pdf?.footerText || "Generated by Iqra School Recorder", marginX, pageH - 22);
    if (pdf?.showCreator !== false) doc.text(createdBy, pageW / 2, pageH - 22, { align: "center" });
    doc.text(`Page ${current} of ${pages}  ·  ${dateLabel(new Date().toISOString().slice(0, 10))}`, pageW - marginX, pageH - 22, {
      align: "right",
    });
  }

  const pageCount = doc.getNumberOfPages();
  if (pdf?.showWatermark) {
    for (let i = 1; i <= pageCount; i += 1) {
      doc.setPage(i);
      doc.setFontSize(58);
      doc.setTextColor(235, 242, 246);
      doc.text(school?.name || "Iqra", pageW / 2, pageH / 2, { align: "center", angle: 30 });
    }
  }
  if (pageCount === 1) footer();

  doc.save(opts.filename.endsWith(".pdf") ? opts.filename : `${opts.filename}.pdf`);
  return { pages: pageCount };
}

/** One-page fee receipt (also used for salary slips). */
export async function buildReceiptPdf(data: {
  settings: Settings | null;
  kind: "fee" | "salary";
  docNo: string;
  date: string;
  personName: string;
  detail: string;
  month: string;
  monthlyAmount: number;
  prevDue: number;
  amount: number;
  remaining: number;
  method: string;
  remarks: string;
  imageUrl?: string | null;
}) {
  const { default: JsPDF } = await import("jspdf");
  const school = data.settings?.school;
  const doc = new JsPDF({ unit: "pt", format: "a4" });
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  const money = (n: number) => `${school?.currencySymbol ?? "Rs."} ${Math.round(n).toLocaleString("en-US")}`;

  doc.setFillColor(7, 114, 92);
  doc.rect(34, 34, w - 68, 74, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(school?.name || "Iqra Islamic Education School", w / 2, 66, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("School Student & Teacher Recorder", w / 2, 82, { align: "center" });
  doc.text(`${school?.address ?? ""}  ·  ${school?.phone ?? ""}`, w / 2, 96, { align: "center" });

  doc.setTextColor(20, 30, 40);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(data.kind === "fee" ? "FEE PAYMENT RECEIPT" : "SALARY PAYMENT SLIP", w / 2, 140, { align: "center" });

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  let y = 172;
  const line = (label: string, value: string, bold = false) => {
    doc.setTextColor(110, 120, 130);
    doc.text(label, 60, y);
    doc.setTextColor(20, 30, 40);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.text(value, 210, y);
    doc.setFont("helvetica", "normal");
    y += 17;
  };
  line("Receipt / Reference No.", data.docNo);
  line("Payment Date", dateLabel(data.date));
  line(data.kind === "fee" ? "Student Name" : "Teacher Name", data.personName);
  line(data.kind === "fee" ? "Class / Father" : "Subject", data.detail);
  line("Fee / Salary Month", data.month);
  line(data.kind === "fee" ? "Monthly Fee" : "Monthly Salary", money(data.monthlyAmount));
  line("Previous Remaining", money(data.prevDue));
  line("Amount Received / Paid", money(data.amount), true);
  line("Still Remaining", money(data.remaining));
  line("Payment Method", data.method);
  if (data.remarks) line("Remarks", data.remarks);

  doc.setDrawColor(200, 210, 220);
  doc.line(60, y + 6, w - 60, y + 6);

  const boxY = y + 26;
  doc.setFillColor(246, 250, 252);
  doc.rect(60, boxY, w - 120, 62, "F");
  doc.setTextColor(7, 114, 92);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(`TOTAL ${data.kind === "fee" ? "FEE RECEIVED" : "SALARY PAID"}: ${money(data.amount)}`, w / 2, boxY + 36, {
    align: "center",
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(110, 120, 130);
  doc.text("Authorised Signature ______________________", w - 60, boxY + 110, { align: "right" });
  doc.text(
    "This is a computer generated receipt.",
    60,
    boxY + 110,
  );
  doc.text(school?.createdBy ?? "Created by Mr. AbdulWahid", w / 2, h - 44, { align: "center" });

  doc.save(`receipt-${data.docNo}.pdf`);
}
